drop table room if exists;
drop table item if exists;
drop table color if exists;
drop table dialog if exists;

CREATE TABLE IF NOT EXISTS room (id INT AUTO_INCREMENT PRIMARY KEY, stato VARCHAR(20), descrizione VARCHAR(600), id_room INT);
CREATE TABLE IF NOT EXISTS item (id INT AUTO_INCREMENT PRIMARY KEY, stato VARCHAR(20), descrizione VARCHAR(200), id_item INT);
CREATE TABLE IF NOT EXISTS color (id INT AUTO_INCREMENT PRIMARY KEY, descrizione VARCHAR(300));
CREATE TABLE IF NOT EXISTS dialog (id INT AUTO_INCREMENT PRIMARY KEY, testo VARCHAR(500));
CREATE TABLE IF NOT EXISTS score (id INT AUTO_INCREMENT PRIMARY KEY, player VARCHAR(100), score INT, time VARCHAR(10));

INSERT INTO room(id_room, stato, descrizione) VALUES 
(0,'Neutro', 'Ti trovi nella stanza centrale del piano. È un misto tra una serra e un attico vero e proprio ed è enorme. Noti come la vegetazione abbia totalmente preso il sopravvento, ci sono finestre rotte, macerie in giro ed è tutto in disordine. Ci sono tre porte, oltre a quella da cui sei entrato. Alla tua sinistra, una porta normale, con alcune macchie di pittura rossa, gialla e blu. Alla tua destra, un''altra porta normale, con alcune macchie di pittura verde, marrone e viola. Davanti a te, una porta con un sigillo con tutti e 6 i colori.'),
(1,'Neutro', 'Ti trovi nella stanza dei colori primari, almeno così c''è scritto sulla porta. È più ordinata dell''attico centrale, non ci sono macerie o mobili, però è comunque piena di vegetazione. Ci sono 3 porte, oltre a quella dell''attico. A nord, una porta marchiata di rosso. A ovest, una porta marchiata di blu. A sud, una porta marchiata di giallo. Sulla porta rossa c''è scritto "Entra e troverai il primo colore primario".'),
(2,'Neutro', 'Ti trovi nella stanza dei colori secondari, almeno così c''è scritto sulla porta. È più trasandata rispetto alla stanza dei colori primari, infatti noti qualche maceria e mobile in giro, oltre che alcune sculture e dipinti di tuo nonno, ormai rovinati. C''è ancora più vegetazione rispetto all''attico. Ci sono 3 porte, oltre a quella dell''attico. A nord, una porta marchiata di verde. A est, una porta marchiata di marrone. A sud, una porta marchiata di viola. Sulla porta verde c''è scritto "Dopo aver preso i colori primari, entra e troverai il primo colore secondario".'),
(3,'Neutro', 'Questa stanza è stranamente vuota. Ci sono in esposizione al muro alcune delle opere di tuo nonno, tra dipinti e statue, ma a parte quello non c''è altro. Non c''è nemmeno vegetazione o altro, la stanza è immacolata. Sulla porta vedi scritto "Qui giace la prova finale". Non ci sono altre porte oltre a quella da cui sei entrato.'),
(4,'Neutro', 'Ti trovi nella stanza del colore rosso. Ti ricorda molto una vetreria, infatti è piena di strumenti per la lavorazione del vetro e di piccole sculture. Ci sono anche dei camini ai lati della stanza, però noti che la vegetazione non è arrivata fin qui. Non ci sono altre porte oltre a quella da cui sei entrato.'),
(5,'Neutro', 'Ti trovi nella stanza del colore blu. È una delle stanze più suggestive di questo piano. Al centro della stanza c''è una piscina rettangolare. Al suo interno, circa a metà piscina, c''è un interruttore, forse è collegato in qualche modo alla porta. Non ci sono altre porte oltre a quella da cui sei entrato.'),
(6,'Neutro', 'Ti trovi nella stanza del colore giallo. È completamente diversa dalle stanze vista fino ad ora. Noti macchinari vari, cavi elettrici, nastri trasportatori, interruttori vari, sembra una vera e propria fabbrica. Ti conviene fare attenzione nel maneggiare l''elettricità. Non ci sono altre porte oltre a quella da cui sei entrato.'),
(7,'Neutro', 'Ti trovi nella stanza del colore verde. Sembra una vera e propria giungla, la vegetazione ha completamente preso il sopravvento di questa stanza, tant''è che non sembra nemmeno una stanza vera e propria. Sulla porta c''è scritto "Recupera il frutto verde per uscire". Non ci sono altre porte oltre a quella da cui sei entrato.'),
(8,'Neutro', 'Ti trovi nella stanza del colore marrone. È probabilmente la stanza nella quale tuo nonno creava tutte le sue sculture. Vedi tutti gli attrezzi che usava, i tavoli e i piedistalli usurati e persino alcuni dei suoi lavori incompiuti. Non ci sono altre porte oltre a quella da cui sei entrato.'),
(9,'Neutro', 'Ti trovi nella stanza del colore viola. È simile alla stanza del colore giallo, ci sono alcuni macchinari e attrezzi che non avevi visto nel resto della stanza. Però, a differenza di quella stanza, ha un''aria più mistica e misteriosa. Noti dei teli viola in giro, librerie piene di manoscritti ammuffiti e marchingegni strani. Sulla porta vedi scritto "Trova un modo di riempire l''incavo per uscire". Non ci sono altre porte oltre a quella da cui sei entrato.');

INSERT INTO item(id_item, stato, descrizione) VALUES 
(0,'Spento', 'Una torcia semplice, con un tizzone in cima. È spenta.'),
(0,'Acceso', 'Una torcia semplice, con un tizzone in cima. È accesa.'),
(1,'NonSpostato', 'Un cumulo di macerie e mattonelle rotte. Bloccano la porta sinistra.'),
(1,'Spostato', 'Un cumulo di macerie e mattonelle rotte.'),
(2,'Spento', 'Un camino di mattoni, con della legna dentro. Il fuoco è spento.'),
(2,'Acceso', 'Un camino di mattoni, con della legna dentro. Il fuoco riscalda quel lato della stanza.'),
(3,'SenzaLegna', 'Un camino di mattoni. Non c''è nulla dentro.'),
(3,'Spento', 'Un camino di mattoni, con della legna dentro. Il fuoco è spento.'),
(3,'Acceso', 'Un camino di mattoni, con della legna dentro. Il fuoco riscalda quel lato della stanza.'),
(4,'Neutro', 'Un cumulo di rami e legnetti secchi disposti per terra.'),
(5,'Neutro', 'Sembra un normale pennello con la punta macchiata di colore rosso.'),
(6,'Neutro', 'Un''ascia per tagliare la legna. È abbastanza grande, sicuro che fosse di tuo nonno?'),
(7,'NonCresciuto', 'Un piccolo alberello che è riuscito a crescere nei mattoni del pavimento.'),
(7,'Cresciuto', 'Un robusto albero di quercia. Difficile pensare che bastasse colorarlo di blu per farlo crescere così.'),
(7,'Tagliato', 'Della maestosa quercia ora è rimasto solo il tronco. Forse può aiutarti a premere l''interruttore.'),
(7,'Spinto', 'Il tronco sta tenendo premuto l''interruttore. È zuppo d''acqua.'),
(8,'SenzaAcqua', 'Una statua a forma di testa di drago. Tuo nonno aveva dei gusti stravaganti.'),
(8,'ConAcqua', 'Una statua a forma di testa di drago. L''acqua che esce dalla sua bocca ha riempito circa a metà la piscina.'),
(9,'Neutro', 'Sembra un normale pennello con la punta macchiata di colore blu.'),
(10,'Acceso', 'L''interruttore del quadro elettrico. È acceso e sta facendo circolare la corrente nel blocco di ferro.'),
(10,'Spento', 'L''interruttore del quadro elettrico. È spento, ora non circola corrente.'),
(11,'NonSpostatoAcceso', 'Un blocco di ferro. Al suo interno sta scorrendo della corrente, sicuro sia una buona idea spostarlo?'),
(11,'NonSpostatoSpento', 'Un blocco di ferro. Non sembra che stia scorrendo corrente al suo interno.'),
(11,'SpostatoSpento', 'Un blocco di ferro. Collega l''interruttore al filo elettrico accanto alla porta, però non circola corrente.'),
(11,'SpostatoAcceso', 'Un blocco di ferro. Ha permesso il passaggio di corrente fino alla porta.'),
(12,'Neutro', 'Sembra un normale pennello con la punta macchiata di colore giallo.'),
(13,'NonCresciuto', 'Da un bocciolo cresciuto per terra sta germogliando una piccola liana.'),
(13,'Cresciuto', 'Ora la liana è cresciuta considerevolmente, forse puoi usarla come corda.'),
(14,'NonCresciuto', 'Una delle vecchie aiuole del giardino di tuo nonno. Ti rattrista vederla senza piante dentro.'),
(14,'Cresciuto', 'Una delle vecchie aiuole del giardino di tuo nonno. Nell''albero che ci è cresciuto dentro, noti un frutto verde.'),
(14,'SenzaFrutta', 'Una delle vecchie aiuole del giardino di tuo nonno. Dentro c''è cresciuto un albero.'),
(15,'Neutro', 'Sembra un normale pennello con la punta macchiata di colore verde.'),
(16,'NonColorato', 'Un sostegno che probabilmente usava tuo nonno per scolpire statue. Si vede che era un amante di tutti i tipi d''arte.'),
(16,'Colorato', 'È comparso un blocco di pietra sul piedistallo. Ti senti ispirato, ma non sai di preciso perché...'),
(16,'NonSpostatoStatua', 'Piedistallo con una statua sopra, quasi identica a quella disegnata sulla pedana a pressione. Sei sorpreso delle tue abilità da scultore.'),
(16,'SpostatoStatua', 'Piedistallo con una statua sopra. Sembra essere incastrata nell''incavo della pedana a pressione.'),
(17,'Neutro', 'Uno scalpello da scultore. Probabilmente era nel kit degli attrezzi da scultore di tuo nonno.'),
(18,'NonPremuta', 'Una pedana a pressione situata in fondo alla stanza. Al centro c''è un incavo con dentro disegnata una statua.'),
(18,'Premuta', 'Nell''incavo della pedana a pressione c''è ora la tua replica della statua. Premerla ha aperto la porta della stanza.'),
(19,'Neutro', 'Sembra un normale pennello con la punta macchiata di colore marrone.'),
(20,'Rotto', 'Una scala a pioli poggiata sulla libreria. Al momento è rotta quindi non puoi usarla.'),
(20,'Aggiustato', 'Una scala a pioli poggiata sulla libreria. Ora che l''hai aggiustata, puoi raggiungere l''orologio in cima alla libreria.'),
(21,'Rotto', 'Resti di quello che sembra essere un orologio da taschino molto vecchio. Non funziona più.'),
(21,'Aggiustato', 'Orologio da taschino, che ora è funzionante. Ha una forma circolare.'),
(22,'Vuoto', 'Incavità a forma circolare sulla porta d''ingresso. Ha una forma circolare.'),
(22,'Pieno', 'Hai lasciato l''orologio nell''incavo e ora è pieno. Facendo così, la porta d''ingresso si è riaperta.'),
(23,'Neutro', 'Sembra un normale pennello con la punta macchiata di viola.'),
(24,'Ghiacciato', 'Vivaio situato al centro della stanza. Il centro è congelato.'),
(24,'SenzaTerra', 'Vivaio situato al centro della stanza. Il centro è vuoto, non c''è nemmeno la terra per far crescere le piante.'),
(24,'ConTerra', 'Vivaio situato al centro della stanza. Con la terra dentro è più carino, ma manca ancora qualcosa.'),
(24,'ConPianta', 'Vivaio situato al centro della stanza. Colorarlo di verde ha fatto nascere un picccolo germoglio. Prenditene cura!!'),
(24,'ConInsetti', 'Vivaio situato al centro della stanza. Ora che l''hai annaffiato, sembra che stia attirando dei brutti insettacci. Ci vorrebbe proprio la racchetta anti-insetti elettrica qui.'),
(24,'SenzaInsetti', 'Vivaio situato al centro della stanza. Col tempo, l''alberello al centro crescerà forte e vigoroso.'),
(24,'Cresciuto', 'Vivaio situato al centro della stanza. Grazie alla tua maestria con i colori, ora al centro cresce un albero forte e maestoso. Resta solo una cosa da fare ora.');

insert into color (id, descrizione) values 
(0, 'Colore rosso. Si dice che rappresenti la passione, come una fiamma che brucia. Permette di dare fuoco a ciò che tinteggi con questo colore.'),
(1, 'Colore blu. Si dice che rappresenti la pace interiore, come il mare calmo. Permette di annacquare ciò che tinteggi con questo colore, oltre ad attivare alcuni oggetti che generano acqua.'),
(2, 'Colore giallo. Si dice che rappresenti la stravaganza, è un colore eccentrico e attivo come l''elettricità. Permette di scaricare corrente su ciò che tinteggi con questo colore, oltre ad attivare alcuni marchingegni che non puoi normalmente attivare.'),
(3, 'Colore verde. Si dice che rappresenti la vitalità, come una pianta rigogliosa. Permette di far germogliare delle piante e rinvigorisce ciò che tinteggi con questo colore.'),
(4, 'Colore marrone. Si dice che rappresenti la stabilità e la costanza, come le montagne. Fa apparire dei blocchi di terra nei punti che tinteggi con questo colore.'),
(5, 'Colore viola. Si dice che rappresenti la nostalgia e lo scorrere del tempo. Permette o di accelerare lo scorrere del tempo o di far ritornare indietro nel tempo ciò che tinteggi con questo colore.');

insert into dialog (id, testo) values 
(1, 'Il pennello si dissolve appena lo prendi, però senti qualcosa di diverso in te... Hai sbloccato il colore rosso!'),
(2, 'Puoi usare il comando Colora per tinteggiare alcuni oggetti ottenendo effetti particolari. Prova il rosso sulla torcia della prima stanza, poi.'),
(3, 'Il pennello si dissolve appena lo prendi, però senti qualcosa di diverso in te... Hai sbloccato il colore blu!'),
(4, 'Il pennello si dissolve appena lo prendi, però senti qualcosa di diverso in te... Hai sbloccato il colore giallo!'),
(5, 'Il pennello si dissolve appena lo prendi, però senti qualcosa di diverso in te... Hai sbloccato il colore verde!'),
(6, 'Il pennello si dissolve appena lo prendi, però senti qualcosa di diverso in te... Hai sbloccato il colore marrone!'),
(7, 'Il pennello si dissolve appena lo prendi, però senti qualcosa di diverso in te... Hai sbloccato il colore viola!'),
(8, 'Colorandola di rosso, la torcia si accende.'),
(9, 'Colorandola di blu, la torcia si spegne.'),
(10, 'Sposti le macerie, sbloccando la porta a sinistra.'),
(11, 'Si accende il fuoco nel camino di destra.'),
(12, 'Hai messo i legnetti nel camino di sinistra.'),
(13, 'Non è successo niente.'),
(14, 'Si accende il fuoco nel camino di sinistra.'),
(15, 'Si sblocca la porta d''ingresso e la porta della stanza blu.'),
(16, 'Dipingendolo di blu, hai annaffiato l''albero e ora è cresciuto.'),
(17, 'Dipingendola di blu, hai attivato la statua. Da essa inizia a sgorgare dell''acqua che riempie il fossato.'),
(18, 'Hai abbattuto l''albero con l''ascia. Forse ora puoi spingerlo?'),
(19, 'Spingi l''albero nel fossato e la corrente lo spinge sull''interruttore.'),
(20, 'Si sblocca la porta d''ingresso e la porta della stanza gialla.'),
(21, 'Forse devi fare qualcos''altro prima di spingerlo.'),
(22, 'Colorandolo di giallo da acceso, l''interruttore si spegne.'),
(23, 'Spegnendo l''interruttore, hai tolto la corrente al blocco di ferro.'),
(24, 'Colorandolo di giallo da spento, l''interruttore si accende.'),
(25, 'Accendendo l''interruttore, hai ridato la corrente al blocco di ferro.'),
(26, 'Si attiva un circuito vicino alla porta. Si sblocca la porta d''ingresso. È il momento di cercare i colori secondari.'),
(27, 'Hai spostato il blocco. Ora si collega al resto del circuito'),
(28, 'Colorandola di verde, la liana cresce considerevolmente.'),
(29, 'Colorandola di verde, nell''aiuola cresce un albero con dei frutti colorati.'),
(30, 'Usi la liana per raccogliere un frutto verde dall''albero. Il frutto si dissolve, facendo aprire la porta d''ingresso e la porta della stanza marrone.'),
(31, 'Colorandolo di marrone, compare un blocco di pietra sul piedistallo.'),
(32, 'Hai scolpito una statua col blocco di pietra sul piedistallo.'),
(33, 'Hai spinto la statua sulla pedana a pressione. È incastrata nell''incavo ora.'),
(34, 'Si sblocca la porta d''ingresso e la porta della stanza viola.'),
(35, 'Colorandola di viola, hai riportato la scala a quando non era ancora rotta.'),
(36, 'Ora che hai aggiustato la scala, puoi raggiungere la cima della libreria.'),
(37, 'Colorandolo di viola, hai riportato l''orologio a quando non era ancora rotto.'),
(38, 'Inserendo l''orologio nell''incavo, la porta si riapre. Ora sei pronto per la prova finale.'),
(39, 'Hai sciolto il ghiaccio dell''aiuola. Dentro è vuota, non c''è nemmeno del terriccio.'),
(40, 'Colorandola di marrone, hai aggiunto del terriccio nell''aiuola. È ancora vuoto, però.'),
(41, 'Inizia a crescere un germoglio nel vivaio. Con le giuste cure, crescerà bene.'),
(42, 'Hai annaffiato la piantina, ti sembra più forte ora. Sta iniziando ad attirare degli insetti, però.'),
(43, 'Hai scacciato gli insetti usando il giallo. Ora la pianta ha solo bisogno di tempo.'),
(44, 'Colorandolo di viola, hai accelerato la crescita della pianta. Ora è diventata un maestoso albero di quercia.'),
(45, 'Hai abbattuto l''albero maestro con l''ascia.'),
(46, 'Sono passati ormai diversi anni da quando ti sei trasferito a New York. Ormai hai fatto carriera, eppure senti di aver perso qualcosa per strada, forse proprio te stesso. Un giorno, però, ricevi una lettera da Vieste. Il tuo caro nonno, con il quale sei cresciuto, è passato a miglior vita e ti ha lasciato in eredità la sua amata villa di famiglia. La notizia ti ha lasciato scosso, ma allo stesso tempo forse questa è l''opportunità di cui avevi bisogno per ritrovare i colori nella tua anima...'),
(47, 'Decidi quindi di partire per tornare nella villa di tuo nonno. Al tuo arrivo, decidi di fare un giro per la villa per rivivere qualche ricordo d''infanzia. Ti ricordi, però, che tuo nonno ti aveva sempre impedito di salire all''ultimo piano della villa. La curiosità prende il meglio di te e decidi di andare a controllarlo. Forse tuo nonno ti ha lasciato la villa perché ti ritiene pronto per essa?'),
(48, 'Salite le scale, ti ritrovi davanti al portone d''ingresso della stanza principale del piano. Lo apri e ti ritrovi in un''enorme stanza che ti pare un misto tra un attico e una serra. La porta si chiude alle tue spalle e su di essa vedi scritto "Recupera i 6 colori che ormai la tua anima ha perduto. Dovrai poi abbattere l''albero maestro. Solo allora potrai uscire". La tua avventura comincia qui.'),
(49, 'È la replica di un famoso dipinto. Dietro la foto c''è scritto: "Questa è una piccola replica del dipinto che vedi in foto. L''ho fatta per te come mio ultimo lavoro prima di lasciarti. Spero che terrai questo mio ultimo lavoro sempre con te - Nonno"'),
(50, 'Hai finito il gioco! Grazie per aver giocato a The Colors Within Your Soul!'),
(51, 'Premi invio per continuare...'),
(52, 'Dal tronco dell''albero, cade un''altra lettera da tuo nonno. Dentro ci trovi un messaggio per te.'),
(53, '"Caro figliolo, se sei arrivato fin qui vuol dire che avevi bisogno di ritrovare te stesso. Ormai sono passato a miglior vita, ma spero che questo viaggio ti abbia insegnato qualcosa. Hai recuperato tutti i colori e ora la tua anima non è più grigia. Ci saranno momenti nella vita in cui non ce la farai più, in quei momenti ricordati sempre di non smarrire te stesso e di andare sempre avanti, rimettendoti in piedi quando dovessi cadere. Ti voglio bene e sono fiero di te, figliolo - Nonno"'),
(54, 'Dentro la lettera sembra esserci anche una foto, cosa sarà mai?'),
(55, 'Premi il tasto ? in alto per avere un chiarimento sui comandi di gioco.'),
(56, 'Puoi vedere gli oggetti nel tuo inventario in basso a destra.'),
(57, 'Non vale la pena spostare questo oggetto.'),
(58, 'Non puoi mettere una cosa del genere nell''inventario!!'),
(59, 'Non stai lasciando nulla!!'),
(60, 'Non hai ancora ritrovato questo colore...'),
(61, 'Sembra che la pittura non abbia effetto su questo oggetto.'),
(62, 'Non c''è nulla in quella direzione.'),
(63, 'La porta è chiusa.'),
(64, 'Non ho capito cosa mi vuoi dire...\n Il comando potrebbe essere sbagliato o non ho trovato l''oggetto che hai chiesto.'),
(65, 'Si sblocca la porta d''ingresso e la porta della stanza blu.')